namespace UKPS.Api.Persistence.Data.Seeding.SyntheticData;

/// <summary>
/// Mirrors synthetic-medicine-records.json, which is generated by
/// documentation/synthetic-data/generators/transform_synthetic_data.py.
/// </summary>
internal sealed record SyntheticDataSet
{
    public required DateOnly AsOf { get; init; }
    public required SyntheticReferenceData ReferenceData { get; init; }
    public required IReadOnlyList<SyntheticOrganisation> Organisations { get; init; }
    public required IReadOnlyList<SyntheticRecord> Records { get; init; }
}
