import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: ['src/**/*.spec.{ts,tsx}', 'tests/int/**/*.int.spec.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'teamcity'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.spec.{ts,tsx}',
        'src/client/generated/**',
        'src/payload-types.ts',
        'src/migrations/**',
        // Generated by Payload and overwritten on regeneration.
        'src/app/\\(payload\\)/**',
        // Declarative Payload schema config. Access rules live in src/access and stay covered.
        'src/payload.config.ts',
        'src/collections/**',
        'src/globals/**',
        // Local dev showcase of design-system components, to be removed.
        'src/app/portal/components/**',
        // Framework glue with no logic, covered by Playwright smoke tests. See ADR-005.
        'src/app/**/layout.tsx',
        'src/app/**/not-found.tsx',
        'src/app/portal/\\[...notFound\\]/page.tsx',
        'src/styles/fonts.ts',
      ],
      // Baseline ratchet (ADR-005): raise as coverage improves, never lower.
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
  },
})
