import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          environment: 'node',
          include: ['src/**/*.test.ts'],
          setupFiles: ['./vitest.setup.ts'],
        },
      },
      {
        extends: true,
        test: {
          name: 'component',
          environment: 'jsdom',
          include: ['src/**/*.test.tsx'],
          setupFiles: ['./vitest.setup.ts', './vitest.setup.dom.ts'],
        },
      },
      {
        extends: true,
        test: {
          name: 'integration',
          environment: 'node',
          include: ['tests/int/**/*.int.test.ts'],
          setupFiles: ['./vitest.setup.ts'],
        },
      },
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'teamcity'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/test-utils/**',
        'src/client/generated/**',
        'src/payload-types.ts',
        'src/migrations/**',
        // Generated by Payload and overwritten on regeneration.
        'src/app/\\(payload\\)/**',
        // Declarative Payload schema config. Access rules live in src/access and stay covered.
        'src/payload.config.ts',
        'src/collections/**',
        'src/globals/**',
        // Local dev showcase of design-system components, to be removed.
        'src/app/portal/components/**',
        // Framework glue with no logic, covered by Playwright smoke tests. See ADR-005.
        'src/app/**/layout.tsx',
        'src/app/**/not-found.tsx',
        'src/app/portal/\\[...notFound\\]/page.tsx',
        'src/styles/fonts.ts',
      ],
      // Baseline ratchet (ADR-005): raise as coverage improves, never lower.
      thresholds: {
        perFile: false,
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
        // Aggregate 100% also requires 100% in every access file. Vitest's
        // perFile flag applies globally, not independently to each glob.
        'src/access/**': { lines: 100, branches: 100 },
        // Independent aggregate gates for each ADR-005 risk scope.
        'src/lib/**': { lines: 90, branches: 90 },
        'src/**/_lib/**': { lines: 90, branches: 90 },
        'src/**/_actions/**': { lines: 90, branches: 90 },
      },
    },
  },
})
