using System.ComponentModel.DataAnnotations;

namespace UKPS.Api.Application.Authentication.Dtos;

/// <summary>
/// Represents the information required to respond to a multi-factor
/// authentication challenge.
/// </summary>
public sealed record RespondToMultiFactorAuthenticationChallengeCommand
{
    /// <summary>
    /// The associated username for the user.
    /// </summary>
    [Required(AllowEmptyStrings = false)]
    public required string Username { get; init; }

    /// <summary>
    /// Gets the one-time authentication code generated by the user's
    /// authenticator application.
    /// </summary>
    [Required(AllowEmptyStrings = false)]
    public required string Code { get; init; }

    /// <summary>
    /// Gets the authentication session identifier associated with the
    /// outstanding multi-factor authentication challenge.
    /// </summary>
    [Required(AllowEmptyStrings = false)]
    public required string AuthenticationSession { get; init; }
}
