default: format build test

format:
    dotnet csharpier format .

format-check:
    dotnet csharpier check .

build:
    dotnet build

run:
    dotnet ef database update --project src --startup-project src
    dotnet run --project src --launch-profile http

generate-migration name:
    dotnet ef migrations add {{name}} --project src --startup-project src --output-dir Migrations

test:
    dotnet test

coverage:
    dotnet test /p:CollectCoverage=true
    dotnet tool run reportgenerator
