default: format build test

format:
    dotnet csharpier format .

format-check:
    dotnet csharpier check .

build:
    dotnet build

run:
    dotnet run --project src --launch-profile http

test:
    dotnet test

coverage:
    dotnet test /p:CollectCoverage=true
    dotnet tool run reportgenerator
