using CreateNewUserResult = UKPS.Api.Application.Common.Result<UKPS.Api.Application.InternalServices.Identity.CreateNewUserError>;
using InitiatedAuthenticationResult = UKPS.Api.Application.Common.Result<
    UKPS.Api.Application.Authentication.Dtos.AuthenticationCredentialsDto,
    UKPS.Api.Application.InternalServices.Identity.InitiateAuthenticationError
>;
using UpdatePasswordResult = UKPS.Api.Application.Common.Result<UKPS.Api.Application.InternalServices.Identity.UpdatePasswordError>;

namespace UKPS.Api.Application.InternalServices.Identity;

/// <summary>
/// Provides operations for managing user identities and authentication
/// using the underlying identity provider.
/// </summary>
public interface IIdentityService
{
    /// <summary>
    /// Initiates software token (authenticator application) setup for an
    /// authentication session.
    /// </summary>
    /// <param name="authenticationSessionId">
    /// The authentication session identifier associated with the current
    /// authentication flow.
    /// </param>
    /// <param name="cancellationToken">
    /// The token used to cancel the operation.
    /// </param>
    /// <returns>
    /// A result containing the information required to configure a software
    /// token for multi-factor authentication.
    /// </returns>
    Task<AssociateSoftwareTokenResult> AssociateSoftwareToken(
        string authenticationSessionId,
        CancellationToken cancellationToken
    );

    /// <summary>
    /// Creates a new user account.
    /// </summary>
    /// <param name="email">
    /// The email address of the user to create.
    /// </param>
    /// <param name="cancellationToken">
    /// The token used to cancel the operation.
    /// </param>
    /// <returns>
    /// The result of the user creation operation.
    /// </returns>
    Task<CreateNewUserResult> CreateNewUser(string email, CancellationToken cancellationToken);

    /// <summary>
    /// Initiates authentication for the specified user.
    /// </summary>
    /// <param name="userEmail">
    /// The email address of the user to authenticate.
    /// </param>
    /// <param name="newPassword">
    /// The password to use when authenticating the user.
    /// </param>
    /// <param name="cancellationToken">
    /// The token used to cancel the operation.
    /// </param>
    /// <returns>
    /// The result of the authentication attempt.
    /// </returns>
    Task<InitiatedAuthenticationResult> InitiateAuthentication(
        string userEmail,
        string newPassword,
        CancellationToken cancellationToken
    );

    /// <summary>
    /// Marks the specified user's email address as verified.
    /// </summary>
    /// <param name="username">
    /// The username of the user whose email address should be marked as verified.
    /// </param>
    /// <param name="cancellationToken">
    /// The token used to cancel the operation.
    /// </param>
    Task MarkEmailAsVerified(string username, CancellationToken cancellationToken);

    /// <summary>
    /// Updates the password for the specified user.
    /// </summary>
    /// <param name="userEmail">
    /// The email address of the user whose password is to be updated.
    /// </param>
    /// <param name="newPassword">
    /// The new password for the user.
    /// </param>
    /// <param name="cancellationToken">
    /// The token used to cancel the operation.
    /// </param>
    /// <returns>
    /// The result of the password update operation.
    /// </returns>
    Task<UpdatePasswordResult> UpdatePassword(
        string userEmail,
        string newPassword,
        CancellationToken cancellationToken
    );

    /// <summary>
    /// Verifies the software token code supplied by the user to complete
    /// multi-factor authentication setup or authentication.
    /// </summary>
    /// <param name="username">
    /// The username of the user whose software token is being verified.
    /// </param>
    /// <param name="authenticationSessionId">
    /// The authentication session identifier associated with the verification.
    /// </param>
    /// <param name="code">
    /// The one-time password generated by the user's authenticator application.
    /// </param>
    /// <param name="cancellationToken">
    /// The token used to cancel the operation.
    /// </param>
    Task VerifySoftwareToken(
        string username,
        string authenticationSessionId,
        string code,
        CancellationToken cancellationToken
    );
}
